import type { Metadata } from "next";
import { Inter, Source_Sans_3 } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@providers/theme-provider";
import ToggleThemeButton from "@/components/custom/toggle-theme-button";

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter"
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} ${sourceSans.variable} no-scrollbar antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          {children}
          <ToggleThemeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
